#!/bin/bash
SERVER_NAME=orange
DIRECTORY_PATH=/root/chatfiles
ssh $SERVER_NAME << EOF
git init $DIRECTORY_PATH -b master
cd $DIRECTORY_PATH
git config receive.denyCurrentBranch updateInstead
EOF
git remote add deployment $SERVER_NAME:$DIRECTORY_PATH
git push deployment master --force
git remote remove deployment
ssh $SERVER_NAME << EOF
cd $DIRECTORY_PATH/blabber/server
docker build . -t modern-blabber
docker rm -f modern-blabber || true
docker run -d -p 8014:80 -v ./state:/app/state --name modern-blabber --restart unless-stopped modern-blabber
EOF
